In [1]:
import numpy as np
import pandas as pd

In [2]:
def lookup_fn(df, key_col, key_val, val_col, idx=0):
    try:
        result_df = df.loc[df[key_col] == key_val].iloc[0]
        value = result_df[val_col]
        return value
    except IndexError:
        return 0

In [3]:
df1 = pd.read_csv('data/docs2people_flatten.csv') 
df1.head(10)

,local ID,Correct Document ID,person_name,Update_Person_Note_1,role,Update Role to,Source Data from https://docs.google.com/spreadsheets/d/1FOGLzWUCnqeR9FoqH_sUAKdSa6-gG1Rc5ncKtoT5p4k/edit#gid=684112097
0,0.0,Carte_Turche_01,İskenderiye Mukataa müfettişi,delete,Addressee,NaN,NaN
1,2.0,Carte_Turche_01,Porte,delete,Sender,NaN,NaN
2,1.0,Carte_Turche_01,Ülgün kadısı,delete,Addressee,NaN,NaN
3,4.0,Carte_Turche_03,Corci (Georgy-Uskok corsair),NaN,Mentioned,NaN,NaN
4,3.0,Carte_Turche_03,Karlıili Sancakbeyi,delete,Addressee,NaN,NaN
5,5.0,Carte_Turche_05,Sayid Muhammed Ağa,NaN,undetermined,NaN,NaN
6,6.0,Carte_Turche_06,Haleb canibi deftardarı,delete,Addressee,NaN,NaN
7,7.0,Carte_Turche_06,Mustafa Reis,NaN,undetermined,NaN,NaN
8,8.0,Carte_Turche_07,Mehmed Çavuş,Mehmed - Çavuş,undetermined,NaN,NaN
9,15.0,Carte_Turche_09,Corci Mo(u)mlo,NaN,Mentioned,NaN,NaN

In [4]:
df1["related_people_original"] = ""

In [5]:
df2 = pd.read_csv('data/docs2people_needs_review.csv') 
df2.head(2)

,document_id,related_people,name_0,role_0,name_1,role_1,name_2,role_2,name_3,role_3,...,name_37,role_37,name_38,role_38,name_39,role_39,name_40,role_40,name_41,role_41
0,Carte_Turche_01,İskenderiye Mukataa müfettişi|Addressee|Ülgün ...,İskenderiye Mukataa müfettişi,Addressee,Ülgün Kadısı,Addressee,Bar Kadısı,Addressee,Porte,Sender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Carte_Turche_02,Porte|Sender,Porte,Sender,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
for index, row in df1.iterrows():
    document_id = str(row["Correct Document ID"])
    action = str(row["Update_Person_Note_1"])
    if action == "parse":
        related_people_original = lookup_fn(df2, "document_id", document_id, "related_people", idx=0)
        df1.set_value(index, 'related_people_original', related_people_original)

In [7]:
df1.to_csv("report/rel_people.csv", index=False)